name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WordPress Plugin Deploy
        uses: rtCamp/action-wordpress-org-plugin-deploy@master
        env:
          CUSTOM_COMMAND: npm run release
          CUSTOM_PATH: build/woo-payment-bkash
          SLUG: woo-payment-bkash
          WORDPRESS_PASSWORD: ${{ secrets.WORDPRESS_PASSWORD }}
          WORDPRESS_USERNAME: ${{ secrets.WORDPRESS_USERNAME }}
