name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.13.1'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run release

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@develop
        env:
          BUILD_DIR: ./build/woo-payment-bkash/
          ASSETS_DIR: wp-assets
          SLUG: woo-payment-bkash
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}

